// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Multiples.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Multiples;

public abstract class Callback_MultipleServer_getRandomMultiple
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackInt
{
    public final void __completed(Ice.AsyncResult __result)
    {
        MultipleServerPrxHelper.__getRandomMultiple_completed(this, __result);
    }
}
