// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Multiples.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Multiples;

public interface MultipleServerPrx extends Ice.ObjectPrx
{
    public int getRandomMultiple(int factor);

    public int getRandomMultiple(int factor, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getRandomMultiple(int factor);

    public Ice.AsyncResult begin_getRandomMultiple(int factor, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getRandomMultiple(int factor, Ice.Callback __cb);

    public Ice.AsyncResult begin_getRandomMultiple(int factor, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getRandomMultiple(int factor, Callback_MultipleServer_getRandomMultiple __cb);

    public Ice.AsyncResult begin_getRandomMultiple(int factor, java.util.Map<String, String> __ctx, Callback_MultipleServer_getRandomMultiple __cb);

    public Ice.AsyncResult begin_getRandomMultiple(int factor, 
                                                   IceInternal.Functional_IntCallback __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getRandomMultiple(int factor, 
                                                   IceInternal.Functional_IntCallback __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getRandomMultiple(int factor, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_IntCallback __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getRandomMultiple(int factor, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_IntCallback __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public int end_getRandomMultiple(Ice.AsyncResult __result);
}
